version: '3'
services:
  web:
    image: jenkins/jenkins:latest
    restart: always
    networks:
      - web
    volumes:
      - ./jenkins_home:/var/jenkins_home
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:jenkins.local"
      - "traefik.enable=true"
      - "traefik.port=8080"
networks:
  web:
    external: true