version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - web
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:jenkins.local"
      - "traefik.enable=true"
      - "traefik.port=8080"
networks:
  web:
    external: true